name: Build check
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  macos_macports_build_job:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, macos-26]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} (macports)
    steps:
      - uses: actions/checkout@v7
      - uses: melusina-org/setup-macports@v1
      - name: Install ports
        run: port install SoapySDR hackrf
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build

  macos_homebrew_build_job:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, macos-26]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} (homebrew)
    steps:
      - uses: actions/checkout@v7
      - name: Setup tools
        run: brew install soapysdr hackrf
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build

  linux_build_job:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Setup tools
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -y --no-install-recommends cmake ninja-build
          sudo apt-get install -q -y libsoapysdr-dev libhackrf-dev
      - name: Configure
        run: cmake -GNinja -B build
      - name: Build
        run: cmake --build build
